Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwproject\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /hwapp/orders/2 HTTP/1.1" 301 0
Internal Server Error: /hwapp/orders/2/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 50, in client_orders
    client_orders = Order.objects.filter(client_id=client_id)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client_id' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
"GET /hwapp/orders/2/ HTTP/1.1" 500 109732
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/orders/2/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: client_orders() got an unexpected keyword argument 'client_id'
"GET /hwapp/orders/2/ HTTP/1.1" 500 62865
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/orders/2/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: client_orders() got an unexpected keyword argument 'client_id'
"GET /hwapp/orders/2/ HTTP/1.1" 500 62865
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/orders/2/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 54, in client_orders
    orders_last_week = orders.filter(date_ordered__gte=timezone.now() - timedelta(days=7)).distinct()
AttributeError: type object 'datetime.timezone' has no attribute 'now'
"GET /hwapp/orders/2/ HTTP/1.1" 500 67222
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hwapp/orders/2/ HTTP/1.1" 200 338
"GET /hwapp/orders/3 HTTP/1.1" 301 0
"GET /hwapp/orders/3/ HTTP/1.1" 200 339
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /hwapp/orders/3/ HTTP/1.1" 200 148
"GET /hwapp/client_orders/3/ HTTP/1.1" 200 339
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2168
"GET /hwapp/orders/3/ HTTP/1.1" 200 148
"GET /hwapp/client_orders/5 HTTP/1.1" 301 0
Internal Server Error: /hwapp/client_orders/5/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 61, in client_orders
    client = Client.objects.get(id=client_id)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hwapp.models.Client.DoesNotExist: Client matching query does not exist.
"GET /hwapp/client_orders/5/ HTTP/1.1" 500 75288
Watching for file changes with StatReloader
Internal Server Error: /hwapp/client_orders/5/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 61, in client_orders
    client = Client.objects.get(id=client_id)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hwapp.models.Client.DoesNotExist: Client matching query does not exist.
"GET /hwapp/client_orders/5/ HTTP/1.1" 500 75425
"GET /hwapp/client_orders/3 HTTP/1.1" 301 0
"GET /hwapp/client_orders/3/ HTTP/1.1" 200 1509
"GET /hwapp/client_orders/2 HTTP/1.1" 301 0
"GET /hwapp/client_orders/2/ HTTP/1.1" 200 1508
"GET /hwapp/client_orders/3/ HTTP/1.1" 200 1509
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwproject\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2168
"GET /hwapp HTTP/1.1" 301 0
Посетили главную страницу
"GET /hwapp/ HTTP/1.1" 200 313
"GET /hwapp/edit_product HTTP/1.1" 301 0
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 101, in edit_product
    return render(request, "edit_product.html", {"form": form, "message": message})
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /hwapp/edit_product/ HTTP/1.1" 500 131635
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 101, in edit_product
    return render(request, "hwapp/edit_product.html", {"form": form, "message": message})
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hwapp/edit_product.html
"GET /hwapp/edit_product/ HTTP/1.1" 500 81499
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 101, in edit_product
    return render(request, "templates/edit_product.html", {"form": form, "message": message})
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/edit_product.html
"GET /hwapp/edit_product/ HTTP/1.1" 500 81563
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 101, in edit_product
    return render(request, "edit_product.html", {"form": form, "message": message})
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /hwapp/edit_product/ HTTP/1.1" 500 131623
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: hwapp/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 101, in edit_product
    return render(request, "edit_product.html", {"form": form, "message": message})
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: hwapp/base.html
"GET /hwapp/edit_product/ HTTP/1.1" 500 131806
"GET /hwapp/client_orders/3/ HTTP/1.1" 200 1509
Internal Server Error: /hwapp/client_orders/3/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: hwapp/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 77, in client_orders
    return render(request, 'client_orders.html', {
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: hwapp/base.html
"GET /hwapp/client_orders/3/ HTTP/1.1" 500 193826
Watching for file changes with StatReloader
"GET /hwapp/client_orders/3/ HTTP/1.1" 200 1570
Watching for file changes with StatReloader
"GET /hwapp/edit_product/ HTTP/1.1" 200 1405
"POST /hwapp/edit_product/ HTTP/1.1" 200 1464
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2168
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: edit_product() missing 1 required positional argument: 'product_id'
"POST /hwapp/edit_product/ HTTP/1.1" 500 64637
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: edit_product() missing 1 required positional argument: 'product_id'
"POST /hwapp/edit_product/ HTTP/1.1" 500 64637
Not Found: /hwapp/edit_product/1
"GET /hwapp/edit_product/1 HTTP/1.1" 404 3078
Internal Server Error: /hwapp/edit_product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: edit_product() missing 1 required positional argument: 'product_id'
"GET /hwapp/edit_product/ HTTP/1.1" 500 63116
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /hwapp/edit_product/1 HTTP/1.1" 200 1405
Internal Server Error: /hwapp/edit_product/1
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 100, in edit_product
    product.save()
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1835, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\base\operations.py", line 216, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
"POST /hwapp/edit_product/1 HTTP/1.1" 500 130141
"POST /hwapp/edit_product/1 HTTP/1.1" 200 1472
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/11
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 103, in edit_product
    form = ProductForm(instance=product)
TypeError: BaseForm.__init__() got an unexpected keyword argument 'instance'
"GET /hwapp/edit_product/11 HTTP/1.1" 500 66799
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hwapp/edit_product/11
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 111, in edit_product
    form = ProductForm(instance=product)
TypeError: BaseForm.__init__() got an unexpected keyword argument 'instance'
"GET /hwapp/edit_product/11 HTTP/1.1" 500 66823
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2168
Not Found: /hwapp/edit_product/
"GET /hwapp/edit_product/ HTTP/1.1" 404 3097
"GET /hwapp/edit_product/11 HTTP/1.1" 200 1263
"POST /hwapp/edit_product/11 HTTP/1.1" 302 0
Посетили главную страницу
"GET /hwapp/ HTTP/1.1" 200 313
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hwapp/edit_product/11 HTTP/1.1" 200 1281
"GET /hwapp/edit_product/12 HTTP/1.1" 200 1274
"POST /hwapp/edit_product/12 HTTP/1.1" 200 1262
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /hwapp/edit_product/12 HTTP/1.1" 200 1262
Internal Server Error: /hwapp/edit_product/4
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 96, in edit_product
    return render(request, 'edit_product.html', {'form': form, "message": message})
UnboundLocalError: local variable 'message' referenced before assignment
"GET /hwapp/edit_product/4 HTTP/1.1" 500 67476
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /hwapp/edit_product/4 HTTP/1.1" 200 1270
Internal Server Error: /hwapp/edit_product/4
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 92, in edit_product
    return redirect('edit_product')
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_product' with no arguments not found. 1 pattern(s) tried: ['hwapp/edit_product/(?P<product_id>[0-9]+)\\Z']
"POST /hwapp/edit_product/4 HTTP/1.1" 500 88907
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /hwapp/edit_product/4 HTTP/1.1" 200 1256
"POST /hwapp/edit_product/4 HTTP/1.1" 200 1256
"POST /hwapp/edit_product/4 HTTP/1.1" 200 1256
"POST /hwapp/edit_product/4 HTTP/1.1" 200 1258
"GET /hwapp/edit_product/3 HTTP/1.1" 200 1271
"GET /hwapp/edit_product/4 HTTP/1.1" 200 1257
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2168
"GET /hwapp/products HTTP/1.1" 301 0
Internal Server Error: /hwapp/products/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: hwapp_product.photo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py", line 54, in product_list
    return render(request, 'product_list.html', {'products': products})
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: hwapp_product.photo
"GET /hwapp/products/ HTTP/1.1" 500 205971
Watching for file changes with StatReloader
"GET /hwapp/products/ HTTP/1.1" 200 663
Not Found: /hwapp/edit_product/
"GET /hwapp/edit_product/ HTTP/1.1" 404 3280
Not Found: /hwapp/edit_product/
"GET /hwapp/edit_product/ HTTP/1.1" 404 3280
"GET /hwapp/edit_product/2 HTTP/1.1" 200 1399
"GET /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/2/change/ HTTP/1.1" 200 4196
- Broken pipe from ('127.0.0.1', 6731)
- Broken pipe from ('127.0.0.1', 6729)
- Broken pipe from ('127.0.0.1', 6730)
- Broken pipe from ('127.0.0.1', 6732)
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 404 1846
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 404 1840
- Broken pipe from ('127.0.0.1', 6733)
- Broken pipe from ('127.0.0.1', 6734)
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 404 1840
"POST /hwapp/edit_product/2 HTTP/1.1" 302 0
Посетили главную страницу
"GET /hwapp/ HTTP/1.1" 200 313
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hwapp/edit_product/2 HTTP/1.1" 200 1399
"POST /hwapp/edit_product/2 HTTP/1.1" 302 0
"GET /hwapp/products/ HTTP/1.1" 200 663
Watching for file changes with StatReloader
"GET /hwapp/edit_product/2 HTTP/1.1" 200 1399
"POST /hwapp/edit_product/2 HTTP/1.1" 302 0
"GET /hwapp/products/ HTTP/1.1" 200 699
Watching for file changes with StatReloader
"GET /hwapp/products/ HTTP/1.1" 200 663
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4631
Watching for file changes with StatReloader
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4631
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5945
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/auth/user/ HTTP/1.1" 200 11917
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/auth/user/add/ HTTP/1.1" 200 11239
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 23739
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 12659
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/add/ HTTP/1.1" 200 11239
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/3/change/ HTTP/1.1" 200 23739
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/add/ HTTP/1.1" 200 11533
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 23739
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 13679
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/ HTTP/1.1" 200 7784
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/add/ HTTP/1.1" 200 12863
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 9525
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/ HTTP/1.1" 200 13764
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 23523
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 13987
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/logout/ HTTP/1.1" 200 3817
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 4899
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 5885
"POST /admin/logout/ HTTP/1.1" 200 3817
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 10935
Internal Server Error: /admin/hwapp/product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: hwapp_product.category_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: hwapp_product.category_id
"GET /admin/hwapp/product/ HTTP/1.1" 500 172319
"GET /admin/ HTTP/1.1" 200 10935
"GET /admin/hwapp/client/ HTTP/1.1" 200 11117
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/ HTTP/1.1" 200 10935
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 10935
Internal Server Error: /admin/hwapp/category/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: hwapp_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.get_results(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\views\main.py", line 312, in get_results
    result_count = paginator.count
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 629, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\query.py", line 615, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: hwapp_category
"GET /admin/hwapp/category/ HTTP/1.1" 500 192845
"GET /admin/ HTTP/1.1" 200 10935
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2168
"GET /admin/ HTTP/1.1" 200 10485
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 10935
"GET /admin/hwapp/category/ HTTP/1.1" 200 8858
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/ HTTP/1.1" 200 10935
Internal Server Error: /admin/hwapp/product/
Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: hwapp_product.category_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\contrib\admin\options.py", line 2124, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\админ\PycharmProjects\DjangoHW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: hwapp_product.category_id
"GET /admin/hwapp/product/ HTTP/1.1" 500 172014
"GET /admin/ HTTP/1.1" 200 10935
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 10935
"GET /admin/hwapp/product/ HTTP/1.1" 200 16233
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/12/change/ HTTP/1.1" 200 12713
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/ HTTP/1.1" 200 16233
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/hwapp/category/ HTTP/1.1" 200 8858
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/category/ HTTP/1.1" 200 8858
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/category/add/ HTTP/1.1" 200 9699
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/hwapp/category/add/ HTTP/1.1" 302 0
"GET /admin/hwapp/category/add/ HTTP/1.1" 200 9986
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/hwapp/category/add/ HTTP/1.1" 302 0
"GET /admin/hwapp/category/ HTTP/1.1" 200 10924
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 16233
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/12/change/ HTTP/1.1" 200 14548
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/category/1/change/?_to_field=id HTTP/1.1" 200 9978
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/12/change/ HTTP/1.1" 200 14548
"GET /admin/hwapp/product/ HTTP/1.1" 200 16233
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 16374
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?o=1 HTTP/1.1" 200 17016
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?o=2.1 HTTP/1.1" 200 17524
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?o=3.2.1 HTTP/1.1" 200 17955
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?o=3.1 HTTP/1.1" 200 17524
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/?o=3.1 HTTP/1.1" 200 17524
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/ HTTP/1.1" 200 17164
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/ HTTP/1.1" 200 17164
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 18908
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-04-06&date_added__lt=2024-04-14 HTTP/1.1" 200 20098
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-04-01&date_added__lt=2024-05-01 HTTP/1.1" 200 20098
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01 HTTP/1.1" 200 20098
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01&price=12.00 HTTP/1.1" 200 12309
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01&price=14.54 HTTP/1.1" 200 15098
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01&price=12.00 HTTP/1.1" 200 12309
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01&price=2.00 HTTP/1.1" 200 15065
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01&price=70.00 HTTP/1.1" 200 15079
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?date_added__gte=2024-01-01&date_added__lt=2025-01-01&price=48.00 HTTP/1.1" 200 15081
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/? HTTP/1.1" 200 18908
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 18908
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/order/ HTTP/1.1" 200 31111
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/ HTTP/1.1" 200 18908
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 18908
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 19399
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?q=description HTTP/1.1" 200 19324
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/?q=kdnvksfdv HTTP/1.1" 200 12144
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/ HTTP/1.1" 200 19399
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/11/change/ HTTP/1.1" 200 14628
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/ HTTP/1.1" 200 19399
"GET /admin/hwapp/product/?q=%D1%82%D0%BE%D0%B2%D0%B0%D1%80 HTTP/1.1" 200 15049
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 19492
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/hwapp/product/ HTTP/1.1" 302 0
"GET /admin/hwapp/product/ HTTP/1.1" 200 19486
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/11/change/ HTTP/1.1" 200 13327
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/11/change/ HTTP/1.1" 200 13861
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\админ\PycharmProjects\DjangoHW\hwproject\hwapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/hwapp/product/ HTTP/1.1" 200 19486
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/hwapp/product/1/change/ HTTP/1.1" 200 14938
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
